# Generated by Django 5.1.7 on 2025-03-29 05:16

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('company', models.CharField(max_length=250)),
                ('job_type', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('on-site', 'On Site')], default='remote', max_length=20)),
                ('employee_type', models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('freelancer', 'Freelancer')], default='full-time', max_length=20)),
                ('body', ckeditor.fields.RichTextField()),
                ('min_salary', models.PositiveIntegerField()),
                ('max_salary', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=250)),
                ('employees_range', models.CharField(choices=[('small', '1-10'), ('medium', '10-50'), ('large', '50-200')], default='small', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
