# Generated by Django 5.1.7 on 2025-03-29 04:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('company', models.CharField(max_length=250)),
                ('body', ckeditor.fields.RichTextField()),
                ('min_salary', models.PositiveIntegerField()),
                ('max_salary', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=250)),
                ('employees_range', models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('freelancer', 'Freelancer')], default='small', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
