# Generated by Django 5.1.7 on 2025-03-29 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
