# Generated by Django 5.1.7 on 2025-03-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='employee_type',
            field=models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('freelancer', 'Freelancer')], default='full-time', max_length=20),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='job_type',
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('on-site', 'On Site')], default='remote', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='employees_range',
            field=models.CharField(choices=[('small', '1-10'), ('medium', '10-50'), ('large', '50-200')], default='small', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
